# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ed6780aa3ac383543d63ab92b1d37f1c9ece1f59314a2f1d0d12a458da4342e698bcb6c4f3fdf4fd2516e76015b64a307fbb741c82135680b893aa96ec07b8

test:
  secret_key_base: ab55b0d0c72702021d2586472bbe72b76515f16f356a06776f79c8532f8485ec5d98e3633eade4b80cc6ee6d207c01a7b3a072115eb8232c750bc10323de0546

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
